#!/usr/bin/php
<?
error_reporting(E_ALL);
ini_set('display_errors', '1');


//The bootstrap
if(chdir(dirname(realpath( __FILE__ )))){
    include('../etc/config.php');
}else{
    echo("Unable to load config.\n");
};

if(require_once('../lib/libmoulin.php')){
}else{
    die("Unable to load Moulin library.\n");
};
// Used for writing init script
$config->exePath = dirname(__FILE__); 

//Start Moulin.
$moulin = new Moulin($config);
       
exit();

?>