#!/usr/bin/php
<?
error_reporting(E_ALL);
ini_set('display_errors', '1');


//Sig handler sets this true to die gracefully from the loop
$isDying = false;
declare(ticks = 1);
pcntl_signal(SIGINT, "signal_handler");

//The bootstrap
if(chdir(dirname(realpath( __FILE__ )))){
    $moulinLibExecPath = dirname(__FILE__);
    $moulinRootPath = preg_replace("/libexec$/", '', $moulinLibExecPath);
    $moulinEtcPath = $moulinRootPath . "etc/";
    $config = parse_ini_file($moulinEtcPath . 'moulin-worker.ini', TRUE);
    $config['environment']['libexec_path']  = $moulinLibExecPath;
    $config['environment']['approot_path']  = $moulinRootPath;
    $config['environment']['etc_path']      = $moulinEtcPath;
}else{
    echo("Unable to load config.\n");
};

if(require_once('../lib/libmoulin.php')){
}else{
    die("Unable to load Moulin library.\n");
};

//Start Moulin.
$moulin = new MoulinWorker($config);
       
exit();

function signal_handler($signal) {
    global $isDying;
    switch($signal) {
        case SIGINT:
            $isDying = true;
    }
}

?>